# buildspec.yml
version: 0.2

env:
  secrets-manager:
    GITHUB_TOKEN: "allen-ms-github-token"
    PRIVATE_KEY: "allen-kp-sshkey"
  variables:
    AWS_DEFAULT_REGION: "ap-southeast-1"
    AWS_ACCOUNT_ID: "642588679360"
    DOCKER_REPO: "ms-solutions-techpulse-webapp"

phases:
  install:
    runtime-versions:
      java: corretto11
    commands:
      - echo "Updating package lists and installing Maven on Ubuntu..."
      - apt-get update
      - apt-get install -y maven

  pre_build:
    commands:
      - echo "Logging in to Amazon ECR..."
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com
      
      - echo "Setting up SSH access..."
      - mkdir -p ~/.ssh
      - echo "$PRIVATE_KEY" > ~/.ssh/id_rsa
      - chmod 600 ~/.ssh/id_rsa
      - ssh-keyscan -H 13.250.100.56 >> ~/.ssh/known_hosts

  build:
    commands:
      - echo "Building the Java application with Maven..."
      - mvn clean package
      
      - echo "Building the Docker image..."
      - IMAGE_TAG=$(date +%Y%m%d%H%M%S)  # Create a unique tag based on timestamp
      - docker build -t java-app:$IMAGE_TAG .
      - docker tag java-app:$IMAGE_TAG $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$DOCKER_REPO:$IMAGE_TAG

  post_build:
    commands:
      - echo "Checking for previous 'latest' tag in ECR..."
      - LATEST_TAG=$AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$DOCKER_REPO:latest
      
      # Untag the previous 'latest' tag if it exists
      - if aws ecr describe-images --repository-name $DOCKER_REPO --image-ids imageTag=latest --region $AWS_DEFAULT_REGION >/dev/null 2>&1; then
          echo "Untagging previous 'latest' image...";
          aws ecr batch-delete-image --repository-name $DOCKER_REPO --image-ids imageTag=latest --region $AWS_DEFAULT_REGION;
        else
          echo "No previous 'latest' tag found.";
        fi

      # Tag the new image as 'latest'
      - echo "Tagging the new image as 'latest'..."
      - docker tag java-app:$IMAGE_TAG $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$DOCKER_REPO:latest

      # Push both the unique tag and 'latest' tag to ECR
      - echo "Pushing the Docker images to ECR..."
      - docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$DOCKER_REPO:$IMAGE_TAG
      - docker push $LATEST_TAG

artifacts:
  files:
    - 'target/*.war'
